import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {AboutMe} from '../components/About'

export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        
      </div>
      <div className={styles.top}>
        <div className={styles.textmain}>
          Welcome to my portfolio!
        </div>
      </div>
    </div>
    <AboutMe />
    <footer className={styles.footer}>
        <div> Copyright © 2021 sugar.</div>
    </footer>
    </>
  )
}
