import Head from 'next/head';
import { motion, useMotionValue, useTransform } from 'framer-motion';
import { Link, animateScroll as scroll } from 'react-scroll';
import ArrowForwardIosIcon from '@material-ui/icons/ArrowForwardIos';
import { Layout } from '../components/Layout';
import styles from '../styles/Home.module.css';
import AboutMe from '../components/About';
import Career from '../components/Career';

const Home: React.FunctionComponent = () => {
  const config = {
    type: 'spring',
    damping: 50,
    stiffness: 100,
  };
  const scrollToTop = () => {
    scroll.scrollToTop();
  };

  return (
    <>
      <Layout>
        <div className={styles.container}>
          <Head>
            <title>My Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div />
          {/* <div className={styles.top}>
            <motion.h1
              transition={config}
              initial={{ scale: 0, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              className={styles.section}
            >
              Welcome to MyPortfolio!!!
            </motion.h1> */}
          <div className={styles.context}>
            <h1>Welcome to MyPortfolio!!!</h1>
          </div>

          <div className={styles.area}>
            <ul className={styles.circles}>
              <li />
              <li />
              <li />
              <li />
              <li />
              <li />
              <li />
              <li />
              <li />
              <li />
            </ul>
          </div>
          <Link
            activeClass="active"
            to="section1"
            spy
            smooth
            offset={-70}
            duration={500}
          >
            <div className={styles.btnCircleBorderSimple}>About Me!</div>
          </Link>
        </div>
        {/* </div> */}
        <AboutMe />
        {/* <Career /> */}
        <div className={styles.spacer} />
        <footer className={styles.footer}>
          <div> Copyright © 2021 sugar.</div>
        </footer>
      </Layout>
    </>
  );
};

export default Home;
